### ISSUE TITLE
Problem with model.clone()

### ISSUE THREAD

**Issue by martinlissmyr** [Oktavilla/backbone-kinship#1]
When cloning a kinship model it's relational properties does not get included... I'm guessing because (original backbone code):

```
clone: function() {
  return new this.constructor(this.attributes);
}
```

... the relational attributes are gone at this point.

ping @snurra

**Comment by snurra** [comment]
Good find.

We can probably just overload that method and use this.toJSON() instead of this.attributes.

**Comment by snurra** [comment]
@martinlissmyr Here you go: https://github.com/Oktavilla/backbone-kinship/releases/tag/v0.1.3
