### ISSUE TITLE
Shouldn't all relations be properly set up, unregarded of whether they have a value or not?

### ISSUE THREAD

**Issue by snurra** [Oktavilla/backbone-kinship#3]
Currently a relation is only set up (ie an instance is created) when a value is set for that relation. Before that it's undefined. 

This leaves instancing up to other places in code where you always have to check whether a relation is set up or not before trying to modify it, to avoid errors. I think it would be leaner if you could rely on all relations being set up, with or without values.

@martinlissmyr Any thoughts on why/where this might be bad idea?

**Comment by martinlissmyr** [comment]
I think it's probably a good idea as long as we only instantiate the relationship when we have a "value" for the property being relationshipified.

**Comment by snurra** [comment]
Maybe I was unclear, because what I suggested was the exact opposite - that we _always_ set up an instance (empty or not) for a relation.

Example:

```
var model = new Backbone.RelationalModel.extend({
  relations: {
    stuff: Backbone.Collection
  }
});

// This breaks because `stuff` is undefined, but maybe it shouldn't be?
model.stuff.add(new Backbone.Model());

// The current way of doing this correctly
if (!model.stuff) {
  // This might be in a view somewhere, which has to know which class to use
  model.stuff = new Backbone.Collection; 
}
model.stuff.add(new Backbone.Model());
```

**Comment by martinlissmyr** [comment]
Ok, then maybe... How do we check that an instance is set if it's always present? 

data:

```
{
   "name": "banana"
}
```

model:

```
var model = new Backbone.RelationalModel.extend({
  relations: {
    stuff: Backbone.Collection
  }
});
```

view:

```
if (model.stuff) {
  // Will do things even though the stuff prop does not exist in the data
}
```

**Comment by martinlissmyr** [comment]
Maybe the problem is that it's a bit different depending on if we have a collection or a model as relationship. A collection could very well be present as it's "just" a list. So an empty collection === no data for the property. A model however is more a "thing" (it can even have data if set on init).

**Comment by snurra** [comment]
Just thought the same. So probably. :)
